### ISSUE TITLE
No user command scroll back history

### ISSUE THREAD

**Issue by BWMerlin** [dm0-/window_merge#1]
Running Windows Vista Ultimate 64bit SP2 with pidgin 2.10.2 and Windows Merge 0.1 user typed commands/chat are not available when using the ctrl + up arrow key.  When I disable Windows Merge I can use ctrl + up arrow and see my previously typed commands/chat.

I am really loving this plugin, have been after something like this for years and I am vary glad you made it, please keep up the great work.

**Comment by dm0-** [comment]
Thanks for reporting, glad it helps.

There is a signal handler to receive certain keyboard input on the Buddy List window that eats these events for conversation widgets.  Can you try to apply the following patch and see if Ctrl+Tab, Ctrl+Up, etc. work?  (I made a wiki page for compiling from source for Windows, but I can upload another DLL later as well.)

The patch simply removes the Buddy List's signal handler to be sure this is the problem you're seeing, so it could be more troublesome than it's worth.  I just don't have Vista to verify it is the same issue as I presume.

I will look into a proper fix and push the commit a bit later.

```
diff --git a/merge.c b/merge.c
index 38a8336..939cc98 100644
--- a/merge.c
+++ b/merge.c
@@ -166,6 +166,13 @@ pwm_merge_conversation(PidginBuddyList *gtkblist)
   /* Clean up the remaining conversation window widget husk. */
   gtk_widget_destroy(gtkconvwin->window);
   gtkconvwin->window = gtkblist->window;
+
+  /* XXX: Testing, this is probably going to break everything. */
+  gulong id;
+  id = g_signal_lookup("key_press_event", G_OBJECT_TYPE(gtkblist->window));
+  id = g_signal_handler_find(gtkblist->window, G_SIGNAL_MATCH_ID, id,
+                             NULL, NULL, NULL, NULL);
+  g_signal_handler_disconnect(gtkblist->window, id);
 }
```

**Comment by dm0-** [comment]
I added the plugin built for Windows to the downloads, and I will try to remember to rebuild it when I push any significant updates here.

I couldn't think of a way to properly correct the issue without modifying the core Pidgin code.  The functions in question are all declared static and inaccessible to plugins.  Perhaps I can submit a bug on their tracker to get the developers' opinions.

Until then, the fix applied here should have relatively minor side effects due to skipping key bindings.  Control+Up/Down and Control+PageUp/PageDown won't have their default effects in GtkIMHtml widgets other than the conversation entries.  Normally they would move the cursor by a paragraph and page-scroll horizontally, respectively.  I think this is an acceptable loss in order to gain message history and tab switching, at least temporarily.

I will close this issue for now, let me know if this doesn't fix the problem on Vista.
